### ISSUE TITLE
eog errors on commit

### ISSUE THREAD

**Issue by vosbergw** [vosbergw/eogMetaEdit#3]
Sometimes after 'Commit' you see the following error on the console and the current photo is no longer shown as selected in the 'Image Gallery' scroll pane.   Updates seem to be OK - the only issue appears to be that after this error if you try to move to the next photo with the right arrow key you will jump back to the first image in the Gallery.   Just clicking on the correct image in the Gallery resolves the error.

See this so far on large png files.  Not sure yet if is due to the size of the file or if it due to adding Exif info to a file that didn't have it previously.

```
Traceback (most recent call last):
  File "/home/wayne/.config/eog/plugins/eogMetaEdit.py", line 271, in fileChanged
    self.currentName = urlparse(Eog.ThumbView.get_first_selected_image(thumb).get_uri_for_display()).path
AttributeError: 'NoneType' object has no attribute 'get_uri_for_display'
Traceback (most recent call last):
  File "/home/wayne/.config/eog/plugins/eogMetaEdit.py", line 271, in fileChanged
    self.currentName = urlparse(Eog.ThumbView.get_first_selected_image(thumb).get_uri_for_display()).path
AttributeError: 'NoneType' object has no attribute 'get_uri_for_display'

(eog:11039): EOG-CRITICAL **: eog_list_store_get_pos_by_image: assertion `EOG_IS_IMAGE (image)' failed

(eog:11039): EOG-CRITICAL **: eog_list_store_get_pos_by_image: assertion `EOG_IS_IMAGE (image)' failed

** (eog:11039): CRITICAL **: manage_exif_data: assertion `image != NULL' failed

(eog:11039): GLib-GObject-CRITICAL **: g_object_unref: assertion `G_IS_OBJECT (object)' failed
```

**Comment by vosbergw** [comment]
wrapping line 271 in eogMetaEdit.py with 

```
try:
except AttributeError: 
    return False
```

fixed the error message from eogMetaEdit but there is no currently selected image after the 'Commit' and I still see the following:

```
(eog:13206): EOG-CRITICAL **: eog_list_store_get_pos_by_image: assertion `EOG_IS_IMAGE (image)' failed

(eog:13206): EOG-CRITICAL **: eog_list_store_get_pos_by_image: assertion `EOG_IS_IMAGE (image)' failed

** (eog:13206): CRITICAL **: manage_exif_data: assertion `image != NULL' failed

(eog:13206): GLib-GObject-CRITICAL **: g_object_unref: assertion `G_IS_OBJECT (object)' failed
```

This may be a bug in EoG [bug 839686](https://bugzilla.redhat.com/show_bug.cgi?id=839686). 

Investigating just making sure the current image gets reselected in the thumbview after my 'Commit'.

**Comment by vosbergw** [comment]
Also modified the 'Commit' to use "Eog.Image.file_changed(<current image>)" to indicate the file was modified, rather than calling my fileChanged() function.   Seems to be working fine now.   Also compiled and tested with EoG 3.5.91 and did not see these errors.  Fixed in branch pngUpdate-issue.3
